---
title: "predictCricketScore_amitavSahay"
author: "Amitav Sahay"
date: "August 8, 2018"
output: html_document
---

# Project Proposal: Predict Cricket Score during a match

## 1. What is the problem you want to solve?
20 overs a side cricket is the short format of a cricket match where each side bats a maximum of 20 overs of 6 balls each and tries to score more runs than the other team. This shortedned version of cricket has caught on with the sports fans and a lot of statistics is now availabe for analysis. Which is perfect because the audience, both on the field and off-field watching on TV, want o guess how each of the two teams playing in a match will fare: how many runs will they score, how fast, which team will win, etc. A particularly popular 20 overs tournament, called IPL T20, is held annually in India and attracts the best cricketers from around the globe, which then brings packed stadiums of spectators and extremely lucrative TV rights.

In this project, I want to predict a team's scoring rate: specifically how many runs will a team score at the end of their 5th over, 10th over, 15th over and the end of the innings which is either at the end of the 20th over or when 10 of its batsmen are out, whichever happens earlier. I will then predict the same for the other team that bats next chasing its opponent's final score: predict the runs it will end up with based on the 2nd team's chase at the end of 5th, 10th and 15th overs.

Based on the score predictions, I will also attempt to predict a win probablility for each side based on the 2nd team's scores at the end of 5th, 10th and 15th overs.

Showing these types of predictions during a match is quite common these days, and while I will not be attempting a new solution, this project will help me apply my data science skills to a real world event. 

I am aware of the following caveats which I will investigate if they have a bearing on the predictive model:

  1. Not all teams have participated in all the 10 years for which data will be analyzed. There are a total of 13 teams across the 10 years. Teams who have not played every year are: 
        Kochi Tuskers Kerala:     2011  only 
        Gujarat Lions:            2016-2017
        Rising Pune Supergiants:  2016, 2017        Pune Warriors:      2011-2013  
        Sunrisers Hyderabad:      2013-2017         Deccan Chargers:    2008-2012  
        Chennai Super Kings did not play in 2016 and 2017. 
        
        For the analysis, we will consider Chennai Super Kings as a regular team since they have played in 8 of the 10 years. And I may combine the two Hyderbad-based teams, Sunrisers Hyderabad and Deccan Chargers, to represent one entity.
        
  2. In 2009, all matches were played in South Africa, not India. 
  
  3. The biggest assumption is that even though some of the players have played for multiple teams over the years, for the analysis to building the score predictive model, I will ignore the individuals and concentrate only on team performance. My reasoning is that even though a player may move from one team to another after a couple of years, any team retains majority of its players from one year to the next; a team's composition changes only gradually over years; typically one star player is replaced with another. 

## 2. Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn’t have otherwise?
An IPL T20 season typically runs for 45 days with about 8 franchises participating. Each franchise has a huge fan following based largely on the region the franchise is located at, but also on specific star cricketers. Matches are held in the evenings after most people have finished their day and are ready to relax in front of their TV sets. Often whole families watch a match since the matches are often close and finish around nap time. There are discussions among those watching together about the scores each of the two teams will put up that evening and who will win. Instead of gut, I can provide these eager spectators (and the TV channel carrying the matches) with better guesstimates based on data science applied to historical data. 

So for instance during a match between Mumbai Indians and Delhi Daredevils, fans of both teams, tens of thousands of them, hope their favorite team will score x number of runs and will restrict the other team to less than that. Fans constantly make and revise these predictions as fortunes fluctuate during a match. This frenzy happens every evening during the tournament for more than a month. If I can build a predictive scoring model based on various relevant historical data, such that the score predictions are mor eaccurate than gut-based, TV commentators and analysts will be able to share this information with the spectators before they unfold, and the involved audience will have more realsitic expectations. With each passing year, more data gets generated, and it is not possible for most human minds to synthesize this data to predict scores accurately. Realistic updates throughout a match makes for a better informed fan and more interactive watching. 

## 3. What data are you going to use for this? How will you acquire this data?
Ball-by-ball data for IPL T20 cricket is available for 10 years, from 2008 through 2017, in total 637 matches. It was originally published by cricsheet.org in YAML format. It has been transformed into four csv files by a data sceintist and is publicly available [here](https://data.world/raghu543/ipl-data-till-2017) . While the largest file with 15,450 rows has the ball-by-ball details of each match, the other 3 csv files contain: a) Details at match level: match id, venue, year and date of the match, result, margin of victory, etc.; b) Names of each of the global 495 players who have particpated for the clubs over the 10 years; and c) which player played in which match for which team; this file has about 14,000 rows. Since I am not focusing on players, I will get all my data from only 3 of the 4  files, and ignore Players.csv file.  

## 4. In brief, outline your approach to solving this problem (knowing that this might change later).
Since historical data will be used to create a predictive model for next year's matches, it becomes necessary to first test the model against historical data. So while some of the 10 year historical data will be used to build the predictive model, another set of the historical data will be used to test the model. We will start with 2008 data, build a predictive model and test a team's scoring pattern with 2009 data. Then use 2008 + 2009 data and test with 2010 data. Then tweak the model with 2008 + 2009 + 2010 data and test against 2011 data. The model will be tweaked iteratively through 2017 data. 

I will evaluate what variables are relevant to predicting final scores for each team in a match. Variables under consideration are: 

  1. Runs scored at the end of 5, 10, 15 overs and at the end of the innings (typically 20, unless all out or target achieved) before that: called Run Rate
  2. Wickets lost (number of men out) at the end of 5, 10, and 15 overs: since early wickets lost may impede the scoring rate
  3. Venue : some grounds are conducive to high scoring matches while some suit bowlers more. This variable may require examining two aspects: a) how this team has scored at this venue and b) how all other teams have averaged on this venue
  4. Whether the team is batting first (setting a target) or second (chasing with the target already known)
  5. Result and scoring pattern of this team against today's opponent over the years
  
Some data wrangling would be necessary for this project. e.g. joining across 2 files; summing the scores at the end of 5th, 10th and 15th overs for each match for each innings. I may pre-sort the two csv files of interest on Season/Year and MatchID columns. In R, I  will then "join" Ball_By_Ball.csv and Match.csv on matchid and Year/Season_Year. Match.csv will provide result of each match and its venue, while Ball_By_Ball.csv file has useful data like Over Id, Ball Id, Number of Runs Scored on that Ball, Did someone get Out on that Ball; and other columns that may not be relevant. Furthermore, Match.csv provides the Team Ids and the sequence of batting for the two teams, and to get the team names, a "join" to the Team.csv file on Team Id will be done. 

Team.csv will drive the building of data because it has Team Names. It will drive the "join" to Match.csv on Team Id, which wil then "join" with Ball_by_Ball.csv which will provide the scores. 

The final data frame for analysis may look like:

  Team Name                                           (from Team.csv)
  
  Year                                                (from Match.csv)
  
  Match Id                                            (from Match.csv)
  
  Venue                                               (from Match.csv)
  
  Opponent Team Name                                  (from Ball_By_Ball.csv; not from Match.csv)
  
  Batting First ? (TRUE/FALSE)                        (from Ball_By_Ball)
  
  Total Overs batted (in terms of number of balls)    (from Ball_By_Ball)
  
  5 Over stage (Runs Scored, and Wickets Lost), 10 over stage, 15 over stage, End of Innings stage  (computed from Ball_By_Ball.csv)
  
  
  To build the model, the data list will be expanded in each iteration with the following year's data (i.e., start with 2008 data, then 2008 + 2009 data, etc.)
  
  ## 5. What are your deliverables? Typically, this would include code, along with a paper and/or a slide deck.
 **Code**: Code for my project w/ documentation will be uploaded to a GitHub repository.
  
**Final Report**: My final report will explain the problem, my approach and findings. This report will also include recommendations for my client for how to use my findings and also delve into future research ideas.

**Slide deck**: slide deck for my project will be uploaded to my GitHub repository.

**Blog/Presentation**:	I will share and present project in an office hours session and promote on a blog



1. I have tried to explore the match data to see what variables may be having an impact on the final score posted by a team in each match. The variables I have considered are: a) Ball by ball run rate (runs scored vs balls batted: maximum 20 overs, each over having 6 balls) b) Opponent team (TeamNameBowl) c) Venue of the match (venueCity) to account for any pitch conditions: some may be more amenable to batting than others d) Impact of how many runs were scored and how many wickets were lost in the initial overs: 1st 4 overs, 1st 6 overs, 1st 8 overs and 1st 10 overs (half way mark). The hypothesis is that if a team loses early wickets, it may not score that many runs by the end, and also if it scores slowly in the beginning (fewer runs in the initial overs), it may be difficult to post a big total at the end of its innings (EOI). 2. To explore the impact of variables on the final score by a team, I have used: a) Box plots b) Histograms and frequency polygon c) Smooth line using lm method d) Facet wraps 3. For the data exploration, I have filtered the data to study one specific team: Chennai Super Kings (abbreviated to CSK) from 2008 through 2014. The idea is that I have to predict how many runs will be scored by a specific team at the end of its innings. Hence we may have to explore batting data of each team separately. 4. Data exploration is performed on 2 wrangled data files: one is summarized and has 1 row per each batting innings, and the other file has rows for each ball bowled in the innings (to show ball by ball scoring rate). The data files are in my github folder: https://github.com/asahay001/springboardIntro 5. I have saved the plots in plots.pdf file for you to see. All my files are in the following github directory: https://github.com/asahay001/springboardIntro The R file to produce the plots is called dataExploreMatchScorePrediction.R The underlying data files after wrangling are saved under the names: a) wrangled_ballByBallDataIPL.csv and b) wrangled_matchSummaryDataIPL.csv 6. The plots show a strong correlation between wickets lost early on (1st 6 overs) with the final score posted by a team. 


Feature Engineering:
1. New columns created for data exploration and liner regression models: TeamBatWinner True/False), summary Scenarios at end of 4, 6, 8,10, 12, 15 overs; 6 overs has aspecial significance: PowerPlay; for Overs rounded correctly to 1 decimal place, from Over-Ball data (an over is 6 legal balls, so 2 over and 3 balls means 2.5 overs for plotting, not 2.3 as in cricket parlance)
2. Ball-by-ball detail rows were summarized into rows by innings, since score prediction is by innings
