---
title: "Readme"
author: "Amitav Sahay"
date: "October 16, 2018"
output: html_document
---

This folder contains the Final Capstone project for "Introduction to Data Science with R".
The project is about using data science principles and R to predict a match winner in an ongoing IPL T20 cricket match,and also what target will the team batting first set for the team batting 2nd in its maximum alloted 20 overs. TV broadcasters and spectactors will beneift from these predictions made with increasing accuracy as a match progreses. 

https://github.com/asahay001/springboardIntro


### Final Report
The final report is contained in execSummaryCricketIPL_predictions.html, which is generated (knit) from its corresponding .Rmd file. 

### Source Code
The driver file for code is interactiveEOIRunAndMatchWinnerPrediction.R, and the source code for called functions are created in the R file: fittingBestModelsForEOIRunsPrediction.R. Source code for Data reading and wrangling are in scorePred_ver1.R and dataWrangling_2018IPLDataForTestingProjectWork.R.  

Data files, sourced from the internet are: Match.csv, Ball_By_Ball.csv, Team.csv, and ipl2018Match_raw.csv.

To read html files on GitHub, please use  http://htmlpreview.github.io


## Documentation Files

execSummaryCricketIPL_predictions.html  
  Final report : knit file
  
dataExploration.html                    
  Graphs and correlations: knit file
  
dataWranglingIPLT20.html                
  Details on data manipulations: knit file
  
execSummaryCricketIPL_predictions.Rmd   
  Final report
dataExploration.Rmd                     
  Graphs and correlations
dataWranglingIPLT20.Rmd                 
  Details on data manipulations

## R Program Files

interactiveEOIRunAndMatchWinnerPrediction.R 
  Driver code to run predictions on treated data
  
fittingBestModelsForEOIRunsPrediction.R     
  Functions that are called by driver program
  
scorePred_ver1.R                            
  Data wrangling code for 2008-2017 data files
  
dataWrangling_2018IPLDataForTestingProjectWork.R    
  Data Wrangling for 2018 season data file
  
dataExploreMatchScorePrediction.R           
  Data Exploration code
  

## Plots
plots.pdf         
  Graphs plotted during data exploration of 2008-2017 data
  

## Data Files

### Raw csv files from source

ipl2018deliveries_raw.csv         IPL Test data containing 2018 season: ball by ball
ipl2018Match_raw.csv              IPL Test data containing 2018 season: 1 row per match
Match.csv                         IPL data 2008-2017 season: 1 row per match
Player.csv                        IPL data 2008-2017 season: player details; not used
Player_match.csv                  IPL data 2008-2017 season: players for a match
Ball_By_Ball.csv                  IPL data 2008-2017 season: details of each ball
Team.csv                          IPL data 2008-2017 season: names of franchises


### R-produced data files

IPL_PredictionParameters_AIC.xlsx               Relevant variables in predictions
MatchByMatchResultPredictionsIPL.csv            Test results of Prediction 2015-2018
MatchPredictionErrorsIPL2015_18.csv             Errors in Prediction 2015-2018
WinPredictionAccuracyIPL2015_18.csv
RMSERunsPredictionIPL2015_18.csv
SummarizedResultPredictionsTestData2018IPL.csv
SummarizedResultPredictionsIPL.csv
wrangled_matchSummaryDataIPL2018only
wrangled_matchSummaryDataIPL.csv                2008 - 2015 data: 1 row per match
wrangled_ballByBallDataIPL.csv                  2008 - 2015 data: each ball as a row
wrangled_inningsSummaryDataIPL.csv              2008 - 2015 data: 1 row per innings; not used


Many thanks to Nathan Sutton for his insights, guidance and encouragement throughout the project.

